### ISSUE TITLE
Error: read ECONNRESET / Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by chesleybrown** [sebinsua/express-keenio#41]
Recently saw this error in my logs.

```
Error from express-keenio not handled with .on('error'): Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)
Error from express-keenio not handled with .on('error'): Error: connect ETIMEDOUT
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
```

I didn't see it actually crashing my application though (I didn't see any application restart in my logs) so if it's just logging this error it's probably not really a problem?

**Comment by sebinsua** [comment]
I don't actually do any network connections directly from my library so if this is happening, then it must be coming from keen-js itself.

I am wondering whether the network misbehaves due to an overly complex event or whether it's just random.

I think what I will do is add a tiny bit of extra logic to the error object relating to the addEvent call that has been made (the event collection that was being used and the event itself). If we can spot a pattern of misbehaviour from this then we can fix it.
